### PR TITLE
Add EIP-1559 support for Trezor Model T

### PR DESCRIPTION
**Pull request by aloisklink**
Adds initial EIP-1559 support.

I've tested this with the latest `develop` branch of Metamask (after modifying `isEIP1559Account` etc to return `true`) and correctly sent an EIP-1559 transaction on the Ropsten test network with my Trezor Model T on the latest v2.4.2 firmware.

To test:
  - Run `yarn pack` to create a `.tgz` (we can't use `yarn link` since MetaMask needs to patch some browser dependencies).
  - Go to Metamask folder and run `yarn add ../path/to/.tgz/`
  - Then run `yarn patch-package` to patch MetaMask dependencies
  - Modify the functions in Metamask `getCurrentAccountEIP1559Compatibility` and `isEIP1559Account` to always return `true`.
  - Finally run `yarn start` to build the dev version of MetaMask.

~Possibly important:~

- [x] ~I haven't tested this yet on my Trezor Model One, which does NOT support EIP-1559, mainly since I can't find a MicroUSB cable anywhere in my house. I don't think it would change anything, but it might be better to hold off on merging until someone tests this.~

## Testing on a Trezor Mode One, which does not currently support EIP-1559

image

Trying to do an EIP-1559 transaction with a Trezor Model One, which currently has no EIP-1559 support, will create an error popup as shown in the screenshot above.

Doing a non-EIP-1559 transaction (e.g. by using this PR's changes, but leaving `getCurrentAccountEIP1559Compatibility` as `false`)  with a Trezor Model One works fine.

### Future work on adding Trezor EIP-1559 support to metamask-extension

I'm not really sure what the best way to add Trezor EIP-1559 support to Metamask would be.

If we just send EIP-1559 transactions to all Trezor devices, Trezor Model T owners will be happy, but Trezor Model One owners won't be able to use new versions of Metamask.

We could add a function like `async supportsEIP1559()` to `eth-trezor-keyring`, but it would have to be `async`, since it needs to poll the hardware wallet over USB, and Metamask's  `isEIP1559Account` is a synchronous function, so won't be able to call it.

But that can be another PR or issue, maybe even in the metamask-extension repo!

### CODE REVIEW

**Comment by aloisklink** [comment]
I've fixed the eslint issues and rebased the lint changes into the last commit.

All tests are passing now.

I've also added tests results for a Trezor Modal One, which unlike the Trezor Model T, does not currently support EIP-1559.

**Comment by aloisklink** [comment]
I've rebased onto the `main` branch to fix merge conflicts by the PRs that @Gudahtt recently made, and so that this PR can run on the new GitHub Actions CI that was added.

**Comment by danjm** [comment]
Thanks a lot for this @aloisklink 

We are going to move this work forward.

I have a question for you: Did this require any modifications to the hd path to get it to work on ropsten? My testing suggests that this won't work on ropsten, which aligns with these comments on the trezor connect repo: https://github.com/trezor/connect/issues/744

**Comment by aloisklink** [comment]
> Thanks a lot for this @aloisklink
> 
> We are going to move this work forward.
> 
> I have a question for you: Did this require any modifications to the hd path to get it to work on ropsten? My testing suggests that this won't work on ropsten, which aligns with these comments on the trezor connect repo: [trezor/connect#744](https://github.com/trezor/connect/issues/744)

No worries! I've got to thank @FrederikBolding! They did the hard work of actually implementing a nice API and wrote the [firmware patch adding EIP-1559 support](https://github.com/trezor/trezor-firmware/pull/1653).

Trezor blocks all testnet transactions by default for security reasons, since the SLIP-0044 standard says that testnet paths should be different from normal Ethereum key derivation paths.

It can be easily disabled by:

```bash
trezorctl set safety-checks prompt
```
(source https://github.com/trezor/trezor-firmware/issues/1474#issuecomment-792048438)

Technically MetaMask is breaking the SLIP-0044 standards by not changing the hd path (see https://github.com/MetaMask/metamask-extension/issues/10450), but to be honest, so many DeFi apps rely on you having the same address in both testnets/mainnets, so it'd be super disruptive if the hd path is changed for testnets.

**Comment by aloisklink** [comment]
Commits were rebased and merged in #108.

Thanks @danjm and @darkwing :rocket:

**Pull request closed without merging**
